import type { City, Review, User, QAPost, Meetup } from "@/types";

export const cities: City[] = [
  {
    id: "1",
    slug: "jeju",
    name: "제주",
    region: "제주",
    description: "천혜의 자연과 카페 문화가 공존하는 디지털 노마드의 성지. 성수기를 피하면 생활비도 합리적이다.",
    thumbnail: "https://images.unsplash.com/photo-1596422846543-75c6fc197f07?w=800&q=80",
    scores: { nomad: 89, cost: 72, internet: 85, cafe: 95, safety: 92, climate: 80, community: 88 },
    monthlyCost: 1200000,
    internetSpeed: 200,
    tags: ["바다", "카페많음", "자연", "핫플"],
    reviewCount: 342,
    currentNomads: 47,
    rank: 1,
    costBreakdown: { housing: 650000, food: 280000, transport: 80000, cafe: 120000, other: 70000 },
    bestSeasons: ["봄", "가을"],
  },
  {
    id: "2",
    slug: "busan",
    name: "부산",
    region: "경상",
    description: "대도시 인프라와 해변의 조화. 카페와 코워킹 스페이스가 풍부하고 교통이 편리하다.",
    thumbnail: "https://images.unsplash.com/photo-1548115184-bc6544d06a58?w=800&q=80",
    scores: { nomad: 85, cost: 78, internet: 88, cafe: 87, safety: 83, climate: 75, community: 82 },
    monthlyCost: 1100000,
    internetSpeed: 250,
    tags: ["바다", "도심", "교통편리", "코워킹"],
    reviewCount: 218,
    currentNomads: 38,
    rank: 2,
    costBreakdown: { housing: 580000, food: 250000, transport: 90000, cafe: 100000, other: 80000 },
    bestSeasons: ["봄", "여름", "가을"],
  },
  {
    id: "3",
    slug: "gangneung",
    name: "강릉",
    region: "강원",
    description: "커피 도시로 유명한 강릉. 바다와 산이 모두 가까워 자연 속 집중력 있는 작업이 가능하다.",
    thumbnail: "https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=800&q=80",
    scores: { nomad: 82, cost: 82, internet: 80, cafe: 92, safety: 90, climate: 72, community: 75 },
    monthlyCost: 950000,
    internetSpeed: 180,
    tags: ["바다", "카페많음", "조용함", "자연"],
    reviewCount: 156,
    currentNomads: 22,
    rank: 3,
    costBreakdown: { housing: 480000, food: 220000, transport: 70000, cafe: 110000, other: 70000 },
    bestSeasons: ["여름", "가을"],
  },
  {
    id: "4",
    slug: "yeosu",
    name: "여수",
    region: "전라",
    description: "밤바다가 아름다운 여수. 최근 카페와 숙박 인프라가 급성장하며 노마드 주목도가 높아지고 있다.",
    thumbnail: "https://images.unsplash.com/photo-1587595431973-160d0d94add1?w=800&q=80",
    scores: { nomad: 78, cost: 85, internet: 75, cafe: 80, safety: 88, climate: 78, community: 70 },
    monthlyCost: 880000,
    internetSpeed: 150,
    tags: ["바다", "야경", "한적함", "감성"],
    reviewCount: 98,
    currentNomads: 14,
    rank: 4,
    costBreakdown: { housing: 420000, food: 200000, transport: 80000, cafe: 100000, other: 80000 },
    bestSeasons: ["봄", "여름"],
  },
  {
    id: "5",
    slug: "gyeongju",
    name: "경주",
    region: "경상",
    description: "역사와 현대가 공존하는 도시. 조용한 환경에서 깊이 있는 작업을 원하는 노마드에게 추천.",
    thumbnail: "https://images.unsplash.com/photo-1563753103688-2c2e4ea5e5ed?w=800&q=80",
    scores: { nomad: 74, cost: 88, internet: 72, cafe: 75, safety: 92, climate: 74, community: 65 },
    monthlyCost: 820000,
    internetSpeed: 140,
    tags: ["역사", "조용함", "한적함", "문화"],
    reviewCount: 67,
    currentNomads: 9,
    rank: 5,
    costBreakdown: { housing: 380000, food: 190000, transport: 70000, cafe: 90000, other: 90000 },
    bestSeasons: ["봄", "가을"],
  },
  {
    id: "6",
    slug: "jeonju",
    name: "전주",
    region: "전라",
    description: "한옥마을과 맛집의 도시 전주. 한국 전통 문화를 느끼며 일하고 싶은 노마드에게 최적.",
    thumbnail: "https://images.unsplash.com/photo-1578469645742-46cae010e5d4?w=800&q=80",
    scores: { nomad: 76, cost: 86, internet: 78, cafe: 83, safety: 89, climate: 72, community: 72 },
    monthlyCost: 860000,
    internetSpeed: 160,
    tags: ["한옥", "카페많음", "맛집", "문화"],
    reviewCount: 112,
    currentNomads: 16,
    rank: 6,
    costBreakdown: { housing: 400000, food: 210000, transport: 65000, cafe: 105000, other: 80000 },
    bestSeasons: ["봄", "가을"],
  },
  {
    id: "7",
    slug: "chuncheon",
    name: "춘천",
    region: "강원",
    description: "호수와 산으로 둘러싸인 낭만 도시. 서울과의 접근성이 좋아 수도권 노마드에게 인기.",
    thumbnail: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80",
    scores: { nomad: 72, cost: 83, internet: 76, cafe: 78, safety: 87, climate: 68, community: 68 },
    monthlyCost: 870000,
    internetSpeed: 155,
    tags: ["호수", "산·숲", "서울근교", "조용함"],
    reviewCount: 84,
    currentNomads: 11,
    rank: 7,
    costBreakdown: { housing: 430000, food: 200000, transport: 75000, cafe: 95000, other: 70000 },
    bestSeasons: ["여름", "가을"],
  },
  {
    id: "8",
    slug: "sokcho",
    name: "속초",
    region: "강원",
    description: "설악산과 동해가 만나는 속초. 여름 시즌 노마드 집중도가 높으며 카페 씬이 빠르게 성장 중.",
    thumbnail: "https://images.unsplash.com/photo-1445299144391-5b50c8d8f8dc?w=800&q=80",
    scores: { nomad: 75, cost: 80, internet: 74, cafe: 79, safety: 88, climate: 70, community: 72 },
    monthlyCost: 900000,
    internetSpeed: 145,
    tags: ["바다", "산·숲", "여름핫플", "감성카페"],
    reviewCount: 91,
    currentNomads: 18,
    rank: 8,
    costBreakdown: { housing: 460000, food: 210000, transport: 70000, cafe: 95000, other: 65000 },
    bestSeasons: ["여름"],
  },
  {
    id: "9",
    slug: "tongyeong",
    name: "통영",
    region: "경상",
    description: "한국의 나폴리로 불리는 통영. 아름다운 다도해와 저렴한 생활비가 장점.",
    thumbnail: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&q=80",
    scores: { nomad: 70, cost: 90, internet: 68, cafe: 72, safety: 90, climate: 76, community: 60 },
    monthlyCost: 790000,
    internetSpeed: 130,
    tags: ["바다", "한적함", "저렴한생활비", "자연"],
    reviewCount: 45,
    currentNomads: 7,
    rank: 9,
    costBreakdown: { housing: 360000, food: 190000, transport: 75000, cafe: 85000, other: 80000 },
    bestSeasons: ["봄", "가을"],
  },
  {
    id: "10",
    slug: "gunsan",
    name: "군산",
    region: "전라",
    description: "근대 역사가 살아 숨쉬는 군산. 독특한 분위기와 저렴한 물가로 조용히 주목받는 도시.",
    thumbnail: "https://images.unsplash.com/photo-1555899434-94d1368aa7af?w=800&q=80",
    scores: { nomad: 65, cost: 92, internet: 65, cafe: 68, safety: 88, climate: 65, community: 58 },
    monthlyCost: 730000,
    internetSpeed: 120,
    tags: ["역사", "한적함", "저렴한생활비", "숨은보석"],
    reviewCount: 32,
    currentNomads: 5,
    rank: 10,
    costBreakdown: { housing: 320000, food: 180000, transport: 70000, cafe: 80000, other: 80000 },
    bestSeasons: ["봄", "가을"],
  },
  {
    id: "11",
    slug: "mokpo",
    name: "목포",
    region: "전라",
    description: "서남해안의 관문 목포. 최근 MZ세대 여행지로 부상하며 카페와 숙박 인프라가 성장 중.",
    thumbnail: "https://images.unsplash.com/photo-1518684079-3c830dcef090?w=800&q=80",
    scores: { nomad: 67, cost: 89, internet: 67, cafe: 70, safety: 86, climate: 72, community: 62 },
    monthlyCost: 760000,
    internetSpeed: 125,
    tags: ["바다", "한적함", "맛집", "숨은보석"],
    reviewCount: 38,
    currentNomads: 6,
    rank: 11,
    costBreakdown: { housing: 340000, food: 185000, transport: 75000, cafe: 85000, other: 75000 },
    bestSeasons: ["봄", "여름"],
  },
  {
    id: "12",
    slug: "pohang",
    name: "포항",
    region: "경상",
    description: "호미곶 일출과 죽도시장이 유명한 포항. 이공계 도시 특성상 인터넷 인프라가 탄탄하다.",
    thumbnail: "https://images.unsplash.com/photo-1559827291-72ee739d0d9a?w=800&q=80",
    scores: { nomad: 69, cost: 84, internet: 82, cafe: 71, safety: 87, climate: 70, community: 64 },
    monthlyCost: 820000,
    internetSpeed: 190,
    tags: ["바다", "인터넷좋음", "도심", "합리적"],
    reviewCount: 54,
    currentNomads: 8,
    rank: 12,
    costBreakdown: { housing: 390000, food: 195000, transport: 75000, cafe: 85000, other: 75000 },
    bestSeasons: ["봄", "가을"],
  },
];

export const reviews: Review[] = [
  {
    id: "r1",
    cityId: "1",
    userId: "u1",
    userNickname: "개발자_지원",
    userJobType: "개발자",
    scores: { internet: 5, cafe: 5, cost: 3, safety: 5, climate: 4, community: 5 },
    body: "제주에서 3개월을 보냈는데 정말 만족스러웠습니다. 애월 쪽 카페들은 맥북 충전도 되고 와이파이도 빵빵해요. 다만 성수기엔 숙박비가 많이 올라서 비수기를 노리는 게 좋아요. 개발자 밋업도 자주 있어서 네트워킹도 됩니다.",
    stayDuration: "1~3개월",
    season: "가을",
    tags: ["카페작업최적", "바다뷰", "개발자많음"],
    helpfulCount: 84,
    createdAt: "2026-02-15",
  },
  {
    id: "r2",
    cityId: "1",
    userId: "u2",
    userNickname: "마케터_수현",
    userJobType: "마케터",
    scores: { internet: 4, cafe: 5, cost: 2, safety: 5, climate: 5, community: 4 },
    body: "제주 노마드 생활 2번째입니다. 커뮤니티가 정말 잘 형성되어 있어요. 제주 노마드 오픈 채팅방에 가입하면 정보 공유도 활발하고 같이 점심 먹을 사람도 찾기 쉬워요. 렌트카 없으면 이동이 불편한 게 단점이에요.",
    stayDuration: "1~4주",
    season: "봄",
    tags: ["커뮤니티좋음", "렌트카필수", "감성카페"],
    helpfulCount: 62,
    createdAt: "2026-01-20",
  },
  {
    id: "r3",
    cityId: "2",
    userId: "u3",
    userNickname: "디자이너_민준",
    userJobType: "디자이너",
    scores: { internet: 5, cafe: 4, cost: 4, safety: 4, climate: 3, community: 4 },
    body: "부산은 서울 다음으로 인프라가 잘 갖춰진 도시라 생활 편의성이 높아요. 해운대/광안리 쪽 카페들은 바다 뷰로 작업하기 좋고, 코워킹도 많습니다. 지하철이 있어서 렌트카 없어도 이동이 편해요.",
    stayDuration: "1~3개월",
    season: "봄",
    tags: ["인프라탄탄", "바다뷰카페", "지하철편리"],
    helpfulCount: 47,
    createdAt: "2026-01-08",
  },
];

export const mockUser: User = {
  id: "u1",
  nickname: "노마드_지원",
  jobType: "개발자",
  bio: "프리랜서 풀스택 개발자. 한국 각지를 탐험 중입니다 🗺️",
  checkinCityId: "1",
  reviewCount: 8,
  favoriteCount: 12,
  visitedCities: 5,
  createdAt: "2025-06-01",
};

export const qaPost: QAPost[] = [
  {
    id: "q1",
    cityId: "1",
    cityName: "제주",
    userId: "u4",
    userNickname: "첫노마드",
    title: "제주 애월 근처에서 장기 숙소 구하는 방법이 궁금해요",
    body: "3개월 정도 제주에 머물려고 하는데, 에어비앤비 말고 더 저렴하게 구할 수 있는 방법이 있을까요?",
    category: "숙소",
    answerCount: 7,
    viewCount: 234,
    isAdopted: true,
    createdAt: "2026-03-10",
  },
  {
    id: "q2",
    cityId: "1",
    cityName: "제주",
    userId: "u5",
    userNickname: "개발자김씨",
    title: "제주 함덕 쪽 와이파이 빠른 카페 추천해 주세요",
    body: "화상회의가 많아서 업로드 속도가 중요한데, 함덕 근처에 좋은 카페 아시는 분 있나요?",
    category: "카페",
    answerCount: 4,
    viewCount: 156,
    isAdopted: false,
    createdAt: "2026-03-18",
  },
  {
    id: "q3",
    cityId: "2",
    cityName: "부산",
    userId: "u6",
    userNickname: "부산탐험가",
    title: "부산 해운대 vs 광안리 어디가 노마드하기 좋아요?",
    body: "부산에서 한 달 살기 계획 중인데, 두 지역 중 어디가 카페나 코워킹 접근성이 더 좋은지 비교해 주실 수 있나요?",
    category: "기타",
    answerCount: 11,
    viewCount: 389,
    isAdopted: true,
    createdAt: "2026-03-05",
  },
  {
    id: "q4",
    cityId: "3",
    cityName: "강릉",
    userId: "u7",
    userNickname: "강원도탐방",
    title: "강릉 겨울 노마드 생활 어떤가요? 날씨가 너무 걱정됩니다",
    body: "강릉 겨울은 많이 춥나요? 11-12월에 방문 예정인데 카페 작업 환경이나 생활 불편함이 있는지 궁금합니다.",
    category: "기타",
    answerCount: 5,
    viewCount: 198,
    isAdopted: false,
    createdAt: "2026-03-20",
  },
  {
    id: "q5",
    cityId: "1",
    cityName: "제주",
    userId: "u8",
    userNickname: "노마드준비생",
    title: "제주 대중교통만으로 생활 가능한가요?",
    body: "운전면허가 없는데 제주에서 렌트카 없이 노마드 생활이 가능할까요? 주로 제주시 내에 머물 예정입니다.",
    category: "교통",
    answerCount: 9,
    viewCount: 312,
    isAdopted: true,
    createdAt: "2026-03-22",
  },
];

export const meetups: Meetup[] = [
  {
    id: "m1",
    cityId: "1",
    cityName: "제주",
    organizerId: "u1",
    organizerNickname: "개발자_지원",
    title: "제주 노마드 4월 네트워킹 모임",
    description: "제주에 머무는 디지털 노마드들의 월간 만남. 각자의 프로젝트와 제주 생활 경험을 나눠요.",
    date: "2026-04-05",
    time: "14:00",
    maxParticipants: 15,
    currentParticipants: 9,
    location: "제주시 애월읍 카페 (추후 공지)",
    tags: ["네트워킹", "프리랜서", "개발자환영"],
  },
  {
    id: "m2",
    cityId: "2",
    cityName: "부산",
    organizerId: "u3",
    organizerNickname: "디자이너_민준",
    title: "부산 노마드 크리에이터 모임",
    description: "디자이너, 마케터, 크리에이터를 위한 부산 노마드 모임. 포트폴리오 피드백도 환영합니다.",
    date: "2026-04-12",
    time: "15:00",
    maxParticipants: 10,
    currentParticipants: 6,
    location: "해운대 코워킹스페이스",
    tags: ["크리에이터", "디자이너", "포트폴리오"],
  },
  {
    id: "m3",
    cityId: "1",
    cityName: "제주",
    organizerId: "u2",
    organizerNickname: "마케터_수현",
    title: "제주 한달살기 입문자 모임",
    description: "제주 노마드를 처음 시작하는 분들을 위한 정보 공유 모임. 숙소, 카페, 생활팁 공유.",
    date: "2026-04-19",
    time: "13:00",
    maxParticipants: 20,
    currentParticipants: 14,
    location: "제주시 구도심 카페",
    tags: ["입문자환영", "정보공유", "제주노마드"],
  },
];

export const checkinStats = [
  { cityName: "제주", count: 47 },
  { cityName: "부산", count: 38 },
  { cityName: "강릉", count: 22 },
  { cityName: "속초", count: 18 },
  { cityName: "전주", count: 16 },
  { cityName: "여수", count: 14 },
];
